// kitchen-sink/react/src/pages/calendar-page.jsx
import React from 'react';
import { Navbar, Page, NavTitle, List, ListItem, Block } from 'framework7-react';

export default class extends React.Component {
  constructor(props) {
    super(props);

    const date = new Date();
    const year = date.getFullYear();
    const month = date.getMonth();
    const day = date.getDate();

    this.state = {
      today: new Date(year, month, day),
      events: [
        {
          date: new Date(year, month, day),
          hours: 12,
          minutes: 30,
          title: 'Meeting with Vladimir',
          color: '#005096',
        },
        {
          date: new Date(year, month, day),
          hours: 18,
          minutes: 0,
          title: 'Shopping',
          color: '#4caf50',
        },
        {
          date: new Date(year, month, day),
          hours: 21,
          minutes: 0,
          title: 'Gym',
          color: '#e91e63',
        },
        {
          date: new Date(year, month, day + 2),
          hours: 16,
          minutes: 0,
          title: 'Pay loan',
          color: '#005096',
        },
        {
          date: new Date(year, month, day + 2),
          hours: 21,
          minutes: 0,
          title: 'Gym',
          color: '#ff9800',
        },
      ],
      eventItems: [],
    }
  }
  render() {
    return (
      <Page onPageInit={this.onPageInit.bind(this)} onPageBeforeRemove={this.onPageBeforeRemove.bind(this)}>
        <Navbar backLink="Back" noShadow>
          <NavTitle className="navbar-calendar-title"></NavTitle>
        </Navbar>
        <Block
          id="calendar"
          strong
          className="no-padding no-margin no-hairline-top"
        ></Block>
        <List
          id="calendar-events"
          noHairlines
          className="no-margin no-safe-area-left"
        >
          {this.state.eventItems.map((item, index) => (
            <ListItem
              key={index}
              title={item.title}
              after={item.time}
            >
              <div className="event-color" style={{'background-color': item.color}} slot="root-start"></div>
            </ListItem>
          ))}
          {this.state.eventItems.length === 0 && (
            <ListItem>
              <span className="text-color-gray" slot="title">No events for this day</span>
            </ListItem>
          )}
        </List>
      </Page>
    );
  }
  renderEvents(calendar) {
    const self = this;
    const currentDate = calendar.value[0];
    const currentEvents = self.state.events
      .filter(event => (
        event.date.getTime() >= currentDate.getTime() &&
        event.date.getTime() < currentDate.getTime() + 24 * 60 * 60 * 1000
      ));

    const eventItems = [];
    if (currentEvents.length) {
      currentEvents.forEach((event) => {
        const hours = event.hours;
        let minutes = event.minutes;
        if (minutes < 10) minutes = `0${minutes}`;
        eventItems.push({
          title: event.title,
          time: `${hours}:${minutes}`,
          color: event.color,
        });
      });
    }
    self.setState({
      eventItems,
    });
  }
  onPageInit(page) {
    const self = this;
    const app = self.$f7;
    const $ = self.$$;
    //const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    const monthNames = ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'];
    self.calendar = app.calendar.create({
      containerEl: '#calendar',
      toolbar: false,
      value: [self.state.today],
      events: self.state.events,
      on: {
        init(calendar) {
          $('.navbar-calendar-title').text(`${monthNames[calendar.currentMonth]}, ${calendar.currentYear}`);
          app.navbar.size(app.navbar.getElByPage(page.el));
          calendar.$el.addClass('no-safe-area-right');
          self.renderEvents(calendar);
        },
        monthYearChangeStart(calendar) {
          $('.navbar-calendar-title').text(`${monthNames[calendar.currentMonth]}, ${calendar.currentYear}`);
          app.navbar.size(app.navbar.getElByPage(page.el));
        },
        change(calendar) {
          self.renderEvents(calendar);
        },
      },
    });
  }
  onPageBeforeRemove() {
    const self = this;
    self.calendar.destroy();
  }
};

// kitchen-sink/svelte/src/pages/calendar-page.svelte
<Page onPageInit={onPageInit} onPageBeforeRemove={onPageBeforeRemove}>
  <Navbar backLink="Back" noShadow>
    <NavTitle class="navbar-calendar-title"></NavTitle>
  </Navbar>
  <Block
    id="calendar"
    strong
    class="no-padding no-margin no-hairline-top"
  ></Block>
  <List
    id="calendar-events"
    noHairlines
    class="no-margin no-safe-area-left"
  >
    {#each eventItems as item, index (index)}
      <ListItem
        title={item.title}
        after={item.time}
      >
        <div class="event-color" style={`background-color: ${item.color}`} slot="root-start"></div>
      </ListItem>
    {/each}
    {#if eventItems.length === 0}
      <ListItem>
        <span class="text-color-gray" slot="title">No events for this day</span>
      </ListItem>
    {/if}
  </List>
</Page>
<script>
  import { f7, Navbar, Page, NavTitle, List, ListItem, Block } from 'framework7-svelte';

  const date = new Date();
  const year = date.getFullYear();
  const month = date.getMonth();
  const day = date.getDate();

  let today = new Date(year, month, day);
  let events = [
    {
      date: new Date(year, month, day),
      hours: 12,
      minutes: 30,
      title: 'Meeting with Vladimir',
      color: '#005096',
    },
    {
      date: new Date(year, month, day),
      hours: 18,
      minutes: 0,
      title: 'Shopping',
      color: '#4caf50',
    },
    {
      date: new Date(year, month, day),
      hours: 21,
      minutes: 0,
      title: 'Gym',
      color: '#e91e63',
    },
    {
      date: new Date(year, month, day + 2),
      hours: 16,
      minutes: 0,
      title: 'Pay loan',
      color: '#005096',
    },
    {
      date: new Date(year, month, day + 2),
      hours: 21,
      minutes: 0,
      title: 'Gym',
      color: '#ff9800',
    },
  ];
  let eventItems = [];

  let calendar;

  function renderEvents(calendar) {
    const currentDate = calendar.value[0];
    const currentEvents = events
      .filter(event => (
        event.date.getTime() >= currentDate.getTime() &&
        event.date.getTime() < currentDate.getTime() + 24 * 60 * 60 * 1000
      ));

    const newEventItems = [];
    if (currentEvents.length) {
      currentEvents.forEach((event) => {
        const hours = event.hours;
        let minutes = event.minutes;
        if (minutes < 10) minutes = `0${minutes}`;
        newEventItems.push({
          title: event.title,
          time: `${hours}:${minutes}`,
          color: event.color,
        });
      });
    }
    eventItems = newEventItems;
  }
  function onPageInit(page) {
    const $ = f7.$;
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

    calendar = f7.calendar.create({
      containerEl: '#calendar',
      toolbar: false,
      value: [today],
      events: events,
      on: {
        init(calendar) {
          $('.navbar-calendar-title').text(`${monthNames[calendar.currentMonth]}, ${calendar.currentYear}`);
          f7.navbar.size(f7.navbar.getElByPage(page.el));
          calendar.$el.addClass('no-safe-area-right');
          renderEvents(calendar);
        },
        monthYearChangeStart(calendar) {
          $('.navbar-calendar-title').text(`${monthNames[calendar.currentMonth]}, ${calendar.currentYear}`);
          f7.navbar.size(f7.navbar.getElByPage(page.el));
        },
        change(calendar) {
          renderEvents(calendar);
        },
      },
    });
  }

  function onPageBeforeRemove() {
    calendar.destroy();
  }
</script>
