// kitchen-sink/vue/src/pages/home.vue
<template>
  <f7-page class="page-home">
    <f7-navbar large transparent :sliding="false">
      <f7-nav-left>
        <f7-link panel-open="left" icon-ios="f7:menu" icon-aurora="f7:menu" icon-md="material:menu"></f7-link>
      </f7-nav-left>
      <f7-nav-title sliding>Framework7 Vue</f7-nav-title>
      <f7-nav-right>
        <f7-link class="searchbar-enable" data-searchbar=".searchbar-components" icon-ios="f7:search" icon-aurora="f7:search" icon-md="material:search"></f7-link>
      </f7-nav-right>
      <f7-nav-title-large>Framework7 Vue</f7-nav-title-large>
      <f7-searchbar
        class="searchbar-components"
        search-container=".components-list"
        search-in="a"
        expandable
        :disable-button="!this.$theme.aurora"
      ></f7-searchbar>
    </f7-navbar>

    <f7-list class="searchbar-hide-on-search">
      <f7-list-item title="关于 Framework7" link="/about/">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
    </f7-list>

    <f7-block-title medium class="searchbar-found">组件</f7-block-title>
    <f7-list class="components-list searchbar-found">
      <f7-list-item link="/accordion/" title="Accordion">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/action-sheet/" title="Action Sheet">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/appbar/" title="Appbar">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/autocomplete/" title="Autocomplete">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/badge/" title="Badge">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/buttons/" title="Buttons">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/calendar/" title="Calendar / Date Picker">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/cards/" title="Cards">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/cards-expandable/" title="Cards Expandable">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/checkbox/" title="Checkbox">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/chips/" title="Chips/Tags">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/color-picker/" title="Color Picker">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/contacts-list/" title="Contacts List">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/content-block/" title="Content Block">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/data-table/" title="Data Table">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/dialog/" title="Dialog">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/elevation/" title="Elevation">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/fab/" title="FAB">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/fab-morph/" title="FAB Morph">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/form-storage/" title="Form Storage">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/gauge/" title="Gauge">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/grid/" title="Grid / Layout Grid">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/icons/" title="Icons">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/infinite-scroll/" title="Infinite Scroll">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/inputs/" title="Inputs">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/lazy-load/" title="Lazy Load">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/list/" title="List View">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/list-index/" title="List Index">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/login-screen/" title="Login Screen">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/menu/" title="Menu">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/messages/" title="Messages">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/navbar/" title="Navbar">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/notifications/" title="Notifications">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/panel/" title="Panel / Side Panels">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/photo-browser/" title="Photo Browser">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/picker/" title="Picker">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/popover/" title="Popover">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/popup/" title="Popup">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/preloader/" title="Preloader">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/progressbar/" title="Progress Bar">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/pull-to-refresh/" title="Pull To Refresh">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/radio/" title="Radio">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/range/" title="Range Slider">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/searchbar/" title="Searchbar">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/searchbar-expandable/" title="Searchbar Expandable">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/sheet-modal/" title="Sheet Modal">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/skeleton/" title="Skeleton (Ghost) Elements">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/smart-select/" title="Smart Select">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/sortable/" title="Sortable List">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/stepper/" title="Stepper">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/subnavbar/" title="Subnavbar">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/swipeout/" title="Swipeout (Swipe To Delete)">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/swiper/" title="Swiper Slider">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/tabs/" title="Tabs">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/text-editor/" title="Text Editor">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/timeline/" title="Timeline">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/toast/" title="Toast">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/toggle/" title="Toggle">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/toolbar-tabbar/" title="Toolbar & Tabbar">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/tooltip/" title="Tooltip">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/treeview/" title="Treeview">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
      <f7-list-item link="/virtual-list/" title="Virtual List">
        <f7-icon slot="media" icon="icon-f7"></f7-icon>
      </f7-list-item>
    </f7-list>
    <f7-list class="searchbar-not-found">
      <f7-list-item title="查无数据"></f7-list-item>
    </f7-list>
    <f7-block-title medium class="searchbar-hide-on-search">主题</f7-block-title>
    <f7-list class="searchbar-hide-on-search">
      <f7-list-item title="iOS Theme" external link="./index.html?theme=ios"></f7-list-item>
      <f7-list-item title="Material (MD) Theme" external link="./index.html?theme=md"></f7-list-item>
      <f7-list-item title="Aurora Desktop Theme" external link="./index.html?theme=aurora"></f7-list-item>
      <f7-list-item title="Color Themes" link="/color-themes/"></f7-list-item>
    </f7-list>

    <f7-block-title medium class="searchbar-hide-on-search">页面加载与路由</f7-block-title>
    <f7-list class="searchbar-hide-on-search">
      <f7-list-item title="Page Transitions" link="/page-transitions/"></f7-list-item>
      <f7-list-item title="Routable Modals" link="/routable-modals/"></f7-list-item>
      <f7-list-item title="Default Route (404)" link="/load-something-that-doesnt-exist/"></f7-list-item>
      <f7-list-item title="Master-Detail (Split View)" link="/master-detail/"></f7-list-item>
    </f7-list>
  </f7-page>
</template>
<script>
  import { f7Page, f7Navbar, f7NavLeft, f7NavTitle, f7NavTitleLarge, f7NavRight, f7BlockTitle, f7List, f7ListItem, f7Link, f7Searchbar, f7Icon } from 'framework7-vue';

  export default {
    components: {
      f7Page,
      f7Navbar,
      f7NavLeft,
      f7NavTitle,
      f7NavTitleLarge,
      f7NavRight,
      f7BlockTitle,
      f7List,
      f7ListItem,
      f7Link,
      f7Searchbar,
      f7Icon,
    },
  };
</script>

// kitchen-sink/svelte/src/pages/home.svelte
<Page class="page-home">
  <Navbar large transparent sliding={false}>
    <NavLeft>
      <Link panelOpen="left" iconIos="f7:menu" iconAurora="f7:menu" iconMd="material:menu"></Link>
    </NavLeft>
    <NavTitle sliding>Framework7 Svelte</NavTitle>
    <NavRight>
      <Link searchbarEnable=".searchbar-components" iconIos="f7:search" iconAurora="f7:search" iconMd="material:search"></Link>
    </NavRight>
    <NavTitleLarge>Framework7 Svelte</NavTitleLarge>
    <Searchbar
      class="searchbar-components"
      searchContainer=".components-list"
      searchIn="a"
      expandable
      disableButton={!theme.aurora}
    />
  </Navbar>

  <List class="searchbar-hide-on-search">
    <ListItem title="关于 Framework7" link="/about/">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
  </List>

  <BlockTitle medium class="searchbar-found">组件</BlockTitle>
  <List class="components-list searchbar-found">
    <ListItem link="/accordion/" title="Accordion">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/action-sheet/" title="Action Sheet">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/appbar/" title="Appbar">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/autocomplete/" title="Autocomplete">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/badge/" title="Badge">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/buttons/" title="Buttons">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/calendar/" title="Calendar / Date Picker">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/cards/" title="Cards">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/cards-expandable/" title="Cards Expandable">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/checkbox/" title="Checkbox">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/chips/" title="Chips/Tags">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/color-picker/" title="Color Picker">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/contacts-list/" title="Contacts List">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/content-block/" title="Content Block">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/data-table/" title="Data Table">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/dialog/" title="Dialog">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/elevation/" title="Elevation">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/fab/" title="FAB">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/fab-morph/" title="FAB Morph">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/form-storage/" title="Form Storage">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/gauge/" title="Gauge">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/grid/" title="Grid / Layout Grid">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/icons/" title="Icons">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/infinite-scroll/" title="Infinite Scroll">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/inputs/" title="Inputs">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/lazy-load/" title="Lazy Load">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/list/" title="List View">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/list-index/" title="List Index">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/login-screen/" title="Login Screen">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/menu/" title="Menu">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/messages/" title="Messages">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/navbar/" title="Navbar">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/notifications/" title="Notifications">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/panel/" title="Panel / Side Panels">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/photo-browser/" title="Photo Browser">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/picker/" title="Picker">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/popover/" title="Popover">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/popup/" title="Popup">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/preloader/" title="Preloader">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/progressbar/" title="Progress Bar">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/pull-to-refresh/" title="Pull To Refresh">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/radio/" title="Radio">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/range/" title="Range Slider">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/searchbar/" title="Searchbar">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/searchbar-expandable/" title="Searchbar Expandable">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/sheet-modal/" title="Sheet Modal">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/skeleton/" title="Skeleton (Ghost) Elements">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/smart-select/" title="Smart Select">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/sortable/" title="Sortable List">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/stepper/" title="Stepper">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/subnavbar/" title="Subnavbar">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/swipeout/" title="Swipeout (Swipe To Delete)">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/swiper/" title="Swiper Slider">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/tabs/" title="Tabs">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/text-editor/" title="Text Editor">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/timeline/" title="Timeline">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/toast/" title="Toast">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/toggle/" title="Toggle">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/toolbar-tabbar/" title="Toolbar & Tabbar">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/tooltip/" title="Tooltip">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/treeview/" title="Treeview">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
    <ListItem link="/virtual-list/" title="Virtual List">
      <i class="icon icon-f7" slot="media" />
    </ListItem>
  </List>
  <List class="searchbar-not-found">
    <ListItem title="查无数据"></ListItem>
  </List>
  <BlockTitle medium class="searchbar-hide-on-search">主题</BlockTitle>
  <List class="searchbar-hide-on-search">
    <ListItem title="iOS Theme" external link="./index.html?theme=ios"></ListItem>
    <ListItem title="Material (MD) Theme" external link="./index.html?theme=md"></ListItem>
    <ListItem title="Aurora Desktop Theme" external link="./index.html?theme=aurora"></ListItem>
    <ListItem title="Color Themes" link="/color-themes/"></ListItem>
  </List>
  <BlockTitle medium class="searchbar-hide-on-search">页面加载与路由</BlockTitle>
  <List class="searchbar-hide-on-search">
    <ListItem title="Page Transitions" link="/page-transitions/"></ListItem>
    <ListItem title="Routable Modals" link="/routable-modals/"></ListItem>
    <ListItem title="Default Route (404)" link="/load-something-that-doesnt-exist/"></ListItem>
    <ListItem title="Master-Detail (Split View)" link="/master-detail/"></ListItem>
  </List>
</Page>

<script>
  import { theme, Page, Navbar, NavLeft, NavTitle, NavTitleLarge, NavRight, BlockTitle, List, ListItem, Link, Searchbar, Icon } from 'framework7-svelte';
</script>
