// kitchen-sink/vue/src/pages/photo-browser.vue
<template>
  <f7-page>
    <f7-navbar title="Photo Browser" back-link="返回"></f7-navbar>
    <f7-block strong>
      <p>Photo Browser is a standalone and highly configurable component that allows to open window with photo viewer and navigation elements with the following features:</p>
      <ul>
        <li>Swiper between photos</li>
        <li>Multi-gestures support for zooming</li>
        <li>Toggle zoom by double tap on photo</li>
        <li>Single click on photo to toggle Exposition mode</li>
      </ul>
    </f7-block>
    <f7-block strong>
      <p>Photo Browser could be opened in a three ways - as a Standalone component (Popup modification), in Popup, and as separate Page:</p>
      <f7-row>
        <f7-col>
          <f7-photo-browser :photos="photos" ref="standalone"></f7-photo-browser>
          <f7-button fill @click="$refs.standalone.open()">Standalone</f7-button>
        </f7-col>
        <f7-col>
          <f7-photo-browser :photos="photos" type="popup" ref="popup"></f7-photo-browser>
          <f7-button fill @click="$refs.popup.open()">Popup</f7-button>
        </f7-col>
        <f7-col>
          <f7-photo-browser :photos="photos" type="page" page-back-link-text="返回" ref="page"></f7-photo-browser>
          <f7-button fill @click="$refs.page.open()">Page</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>
    <f7-block strong>
      <p>Photo Browser suppots 2 default themes - default Light (like in previous examples) and Dark theme. Here is a Dark theme examples:</p>
      <f7-row>
        <f7-col>
          <f7-photo-browser :photos="photos" theme="dark" ref="standaloneDark"></f7-photo-browser>
          <f7-button fill @click="$refs.standaloneDark.open()">Standalone</f7-button>
        </f7-col>
        <f7-col>
          <f7-photo-browser :photos="photos" theme="dark" type="popup" ref="popupDark"></f7-photo-browser>
          <f7-button fill @click="$refs.popupDark.open()">Popup</f7-button>
        </f7-col>
        <f7-col>
          <f7-photo-browser :photos="photos" theme="dark" type="page" page-back-link-text="返回" ref="pageDark"></f7-photo-browser>
          <f7-button fill @click="$refs.pageDark.open()">Page</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>
  </f7-page>
</template>
<script>
  import { f7Navbar, f7Page, f7PhotoBrowser, f7Block, f7Row, f7Col, f7Button } from 'framework7-vue';

  export default {
    components: {
      f7Navbar,
      f7Page,
      f7PhotoBrowser,
      f7Block,
      f7Row,
      f7Col,
      f7Button,
    },
    data() {
      return {
        photos: [
          {
            url: 'img/beach.jpg',
            caption: 'Amazing beach in Goa, India',
          },
          'http://placekitten.com/1024/1024',
          'img/lock.jpg',
          {
            url: 'img/monkey.jpg',
            caption: 'I met this monkey in Chinese mountains',
          },
          {
            url: 'img/mountains.jpg',
            caption: 'Beautiful mountains in Zhangjiajie, China',
          },
        ],
      };
    },
  };
</script>

// kitchen-sink/svelte/src/pages/photo-browser.svelte
<Page>
  <Navbar title="Photo Browser" backLink="返回"></Navbar>
  <Block strong>
    <p>Photo Browser is a standalone and highly configurable component that allows to open window with photo viewer and navigation elements with the following features:</p>
    <ul>
      <li>Swiper between photos</li>
      <li>Multi-gestures support for zooming</li>
      <li>Toggle zoom by double tap on photo</li>
      <li>Single click on photo to toggle Exposition mode</li>
    </ul>
  </Block>
  <Block strong>
    <p>Photo Browser could be opened in a three ways - as a Standalone component (Popup modification), in Popup, and as separate Page:</p>
    <Row>
      <Col>
        <PhotoBrowser photos={photos} bind:this={ standalone } />
        <Button fill onClick={() => standalone.open()}>Standalone</Button>
      </Col>
      <Col>
        <PhotoBrowser photos={photos} type="popup" bind:this={ popup } />
        <Button fill onClick={() => popup.open()}>Popup</Button>
      </Col>
      <Col>
        <PhotoBrowser photos={photos} type="page" pageBackLinkText="返回" bind:this={ page } />
        <Button fill onClick={() => page.open()}>Page</Button>
      </Col>
    </Row>
  </Block>
  <Block strong>
    <p>Photo Browser suppots 2 default themes - default Light (like in previous examples) and Dark theme. Here is a Dark theme examples:</p>
    <Row>
      <Col>
        <PhotoBrowser photos={photos} theme="dark" bind:this={ standaloneDark } />
        <Button fill onClick={() => standaloneDark.open()}>Standalone</Button>
      </Col>
      <Col>
        <PhotoBrowser photos={photos} theme="dark" type="popup" bind:this={ popupDark } />
        <Button fill onClick={() => popupDark.open()}>Popup</Button>
      </Col>
      <Col>
        <PhotoBrowser photos={photos} theme="dark" type="page" pageBackLinkText="返回" bind:this={ pageDark } />
        <Button fill onClick={() => pageDark.open()}>Page</Button>
      </Col>
    </Row>
  </Block>
</Page>
<script>
  import { Navbar, Page, PhotoBrowser, Block, Row, Col, Button } from 'framework7-svelte';

  let standalone;
  let popup;
  let page;

  let standaloneDark;
  let popupDark;
  let pageDark;

  let photos = [
    {
      url: 'img/beach.jpg',
      caption: 'Amazing beach in Goa, India',
    },
    'http://placekitten.com/1024/1024',
    'img/lock.jpg',
    {
      url: 'img/monkey.jpg',
      caption: 'I met this monkey in Chinese mountains',
    },
    {
      url: 'img/mountains.jpg',
      caption: 'Beautiful mountains in Zhangjiajie, China',
    },
  ];
</script>
