// kitchen-sink/react/src/pages/swiper-custom-controls.jsx
import React from 'react';
import { Navbar, Page, Swiper, SwiperSlide } from 'framework7-react';

export default () => (

  <Page>
    <Navbar title="Custom Controls" backLink="返回"></Navbar>
    <div className="demo-swiper-custom">
      <Swiper
        pagination
        navigation
        params={{
          pagination: {
            clickable: true,
          }
        }}
      >
        <SwiperSlide style={{backgroundImage: 'url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-1.jpg)'}} />
        <SwiperSlide style={{backgroundImage: 'url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-2.jpg)'}} />
        <SwiperSlide style={{backgroundImage: 'url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-3.jpg)'}} />
        <SwiperSlide style={{backgroundImage: 'url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-4.jpg)'}} />
        <SwiperSlide style={{backgroundImage: 'url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-5.jpg)'}} />
        <SwiperSlide style={{backgroundImage: 'url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-6.jpg)'}} />
      </Swiper>
    </div>
  </Page>

);

// kitchen-sink/svelte/src/pages/swiper-custom-controls.svelte
<Page>
  <Navbar title="Custom Controls" backLink="返回"></Navbar>
  <div class="demo-swiper-custom">
    <Swiper
      pagination
      navigation
      params={{
        pagination: {
          clickable: true,
        }
      }}
    >
      <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-1.jpg)" />
      <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-2.jpg)" />
      <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-3.jpg)" />
      <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-4.jpg)" />
      <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-5.jpg)" />
      <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-6.jpg)" />
    </Swiper>
  </div>
</Page>
<script>
  import { Navbar, Page, Swiper, SwiperSlide } from 'framework7-svelte';
</script>
