// kitchen-sink/vue/src/pages/swiper-fade.vue
<template>
  <f7-page>
    <f7-navbar title="Fade Effect" back-link="返回"></f7-navbar>
    <div data-pagination='{"el": ".swiper-pagination"}' data-effect="fade" class="swiper-container swiper-init demo-swiper demo-swiper-fade">
      <div class="swiper-pagination"></div>
      <div class="swiper-wrapper">
        <div style="background-image:url(https://cdn.framework7.io/placeholder/people-1024x1024-1.jpg)" class="swiper-slide"></div>
        <div style="background-image:url(https://cdn.framework7.io/placeholder/people-1024x1024-2.jpg)" class="swiper-slide"></div>
        <div style="background-image:url(https://cdn.framework7.io/placeholder/people-1024x1024-3.jpg)" class="swiper-slide"></div>
        <div style="background-image:url(https://cdn.framework7.io/placeholder/people-1024x1024-4.jpg)" class="swiper-slide"></div>
      </div>
    </div>
  </f7-page>
</template>
<script>
  import { f7Navbar, f7Page } from 'framework7-vue';

  export default {
    components: {
      f7Navbar,
      f7Page,
    },
  };
</script>

// kitchen-sink/svelte/src/pages/swiper-fade.svelte
<Page>
  <Navbar title="Fade Effect" backLink="返回"></Navbar>
  <Swiper class="demo-swiper demo-swiper-fade" pagination params={{
    effect: 'fade',
  }}>
    <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/people-1024x1024-1.jpg)" />
    <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/people-1024x1024-2.jpg)" />
    <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/people-1024x1024-3.jpg)" />
    <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/people-1024x1024-4.jpg)" />
  </Swiper>
</Page>
<script>
  import { Navbar, Page, Swiper, SwiperSlide } from 'framework7-svelte';
</script>
