// kitchen-sink/react/src/pages/swiper-fade.jsx
import React from 'react';
import { Navbar, Page, Swiper, SwiperSlide } from 'framework7-react';

export default () => (

  <Page>
    <Navbar title="Fade Effect" backLink="返回"></Navbar>
    <Swiper className="demo-swiper demo-swiper-fade" pagination params={{
      effect: 'fade',
    }}>
      <SwiperSlide style={{backgroundImage: 'url(https://cdn.framework7.io/placeholder/people-1024x1024-1.jpg)'}}></SwiperSlide>
      <SwiperSlide style={{backgroundImage: 'url(https://cdn.framework7.io/placeholder/people-1024x1024-2.jpg)'}}></SwiperSlide>
      <SwiperSlide style={{backgroundImage: 'url(https://cdn.framework7.io/placeholder/people-1024x1024-3.jpg)'}}></SwiperSlide>
      <SwiperSlide style={{backgroundImage: 'url(https://cdn.framework7.io/placeholder/people-1024x1024-4.jpg)'}}></SwiperSlide>
    </Swiper>
  </Page>

);

// kitchen-sink/svelte/src/pages/swiper-fade.svelte
<Page>
  <Navbar title="Fade Effect" backLink="返回"></Navbar>
  <Swiper class="demo-swiper demo-swiper-fade" pagination params={{
    effect: 'fade',
  }}>
    <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/people-1024x1024-1.jpg)" />
    <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/people-1024x1024-2.jpg)" />
    <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/people-1024x1024-3.jpg)" />
    <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/people-1024x1024-4.jpg)" />
  </Swiper>
</Page>
<script>
  import { Navbar, Page, Swiper, SwiperSlide } from 'framework7-svelte';
</script>
