// kitchen-sink/react/src/pages/swiper-nested.jsx
import React from 'react';
import { Navbar, Page, Swiper, SwiperSlide } from 'framework7-react';

export default () => (
  <Page>
    <Navbar title="Nested Swipers" backLink="返回"></Navbar>
    <Swiper className="demo-swiper" pagination>
      <SwiperSlide>Horizontal Slide 1</SwiperSlide>
      <SwiperSlide>
        <Swiper className="demo-swiper" pagination params={{ direction: 'vertical' }}>
          <SwiperSlide>Vertical Slide 1</SwiperSlide>
          <SwiperSlide>Vertical Slide 2</SwiperSlide>
          <SwiperSlide>Vertical Slide 3</SwiperSlide>
        </Swiper>
      </SwiperSlide>
      <SwiperSlide>Horizontal Slide 3</SwiperSlide>
      <SwiperSlide>Horizontal Slide 3</SwiperSlide>
    </Swiper>
  </Page>
);

// kitchen-sink/svelte/src/pages/swiper-nested.svelte
<Page>
  <Navbar title="Nested Swipers" backLink="返回"></Navbar>
  <Swiper class="demo-swiper" pagination>
    <SwiperSlide>Horizontal Slide 1</SwiperSlide>
    <SwiperSlide>
      <Swiper class="demo-swiper" pagination params={{ direction: 'vertical' }}>
        <SwiperSlide>Vertical Slide 1</SwiperSlide>
        <SwiperSlide>Vertical Slide 2</SwiperSlide>
        <SwiperSlide>Vertical Slide 3</SwiperSlide>
      </Swiper>
    </SwiperSlide>
    <SwiperSlide>Horizontal Slide 3</SwiperSlide>
    <SwiperSlide>Horizontal Slide 3</SwiperSlide>
  </Swiper>
</Page>
<script>
  import { Navbar, Page, Swiper, SwiperSlide } from 'framework7-svelte';
</script>
