// kitchen-sink/react/src/pages/tabs.jsx
import React from 'react';
import { Navbar, Page, List, ListItem } from 'framework7-react';

export default () => (
  <Page>
    <Navbar title="Tabs" backLink="返回"></Navbar>
    <List>
      <ListItem link="/tabs-static/" title="Static Tabs"></ListItem>
      <ListItem link="/tabs-animated/" title="Animated Tabs"></ListItem>
      <ListItem link="/tabs-swipeable/" title="Swipeable Tabs"></ListItem>
      <ListItem link="/tabs-routable/" title="Routable Tabs"></ListItem>
    </List>
  </Page>
);

// kitchen-sink/svelte/src/pages/tabs.svelte
<Page>
  <Navbar title="Tabs" backLink="返回"></Navbar>
  <List>
    <ListItem link="/tabs-static/" title="Static Tabs"></ListItem>
    <ListItem link="/tabs-animated/" title="Animated Tabs"></ListItem>
    <ListItem link="/tabs-swipeable/" title="Swipeable Tabs"></ListItem>
    <ListItem link="/tabs-routable/" title="Routable Tabs"></ListItem>
  </List>
</Page>
<script>
  import { Navbar, Page, List, ListItem } from 'framework7-svelte';
</script>
