// kitchen-sink/react/src/pages/swiper-nested.jsx
import React from 'react';
import { Navbar, Page, Swiper, SwiperSlide } from 'framework7-react';

export default () => (
  <Page>
    <Navbar title="Nested Swipers" backLink="返回"></Navbar>
    <Swiper className="demo-swiper" pagination>
      <SwiperSlide>Horizontal Slide 1</SwiperSlide>
      <SwiperSlide>
        <Swiper className="demo-swiper" pagination params={{ direction: 'vertical' }}>
          <SwiperSlide>Vertical Slide 1</SwiperSlide>
          <SwiperSlide>Vertical Slide 2</SwiperSlide>
          <SwiperSlide>Vertical Slide 3</SwiperSlide>
        </Swiper>
      </SwiperSlide>
      <SwiperSlide>Horizontal Slide 3</SwiperSlide>
      <SwiperSlide>Horizontal Slide 3</SwiperSlide>
    </Swiper>
  </Page>
);

// kitchen-sink/vue/src/pages/swiper-nested.vue
<template>
  <f7-page>
    <f7-navbar title="Nested Swipers" back-link="返回"></f7-navbar>
    <div data-pagination='{"el": ".swiper-pagination-h"}' class="swiper-container swiper-init demo-swiper">
      <div class="swiper-pagination swiper-pagination-h"></div>
      <div class="swiper-wrapper">
        <div class="swiper-slide">Horizontal Slide 1</div>
        <div class="swiper-slide">
          <div data-pagination='{"el": ".swiper-pagination-v"}' data-direction="vertical" class="swiper-container swiper-init demo-swiper">
            <div class="swiper-pagination swiper-pagination-v"></div>
            <div class="swiper-wrapper">
              <div class="swiper-slide">Vertical Slide 1</div>
              <div class="swiper-slide">Vertical Slide 2</div>
              <div class="swiper-slide">Vertical Slide 3</div>
            </div>
          </div>
        </div>
        <div class="swiper-slide">Horizontal Slide 3</div>
        <div class="swiper-slide">Horizontal Slide 4</div>
      </div>
    </div>
  </f7-page>
</template>
<script>
  import { f7Navbar, f7Page } from 'framework7-vue';

  export default {
    components: {
      f7Navbar,
      f7Page,
    },
  };
</script>
