// kitchen-sink/svelte/src/pages/swiper-custom-controls.svelte
<Page>
  <Navbar title="Custom Controls" backLink="返回"></Navbar>
  <div class="demo-swiper-custom">
    <Swiper
      pagination
      navigation
      params={{
        pagination: {
          clickable: true,
        }
      }}
    >
      <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-1.jpg)" />
      <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-2.jpg)" />
      <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-3.jpg)" />
      <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-4.jpg)" />
      <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-5.jpg)" />
      <SwiperSlide style="background-image: url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-6.jpg)" />
    </Swiper>
  </div>
</Page>
<script>
  import { Navbar, Page, Swiper, SwiperSlide } from 'framework7-svelte';
</script>

// kitchen-sink/vue/src/pages/swiper-custom-controls.vue
<template>
  <f7-page>
    <f7-navbar title="Custom Controls" back-link="返回"></f7-navbar>
    <div class="demo-swiper-custom">
      <div data-pagination='{"el": ".swiper-pagination", "clickable": true}' data-navigation='{"nextEl": ".swiper-button-next", "prevEl": ".swiper-button-prev"}' data-space-between="0" class="swiper-container swiper-init">
        <div class="swiper-pagination"></div>
        <div class="swiper-wrapper">
          <div style="background-image:url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-1.jpg)" class="swiper-slide"></div>
          <div style="background-image:url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-2.jpg)" class="swiper-slide"></div>
          <div style="background-image:url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-3.jpg)" class="swiper-slide"></div>
          <div style="background-image:url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-4.jpg)" class="swiper-slide"></div>
          <div style="background-image:url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-5.jpg)" class="swiper-slide"></div>
          <div style="background-image:url(https://cdn.framework7.io/placeholder/nightlife-1024x1024-6.jpg)" class="swiper-slide"></div>
        </div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
      </div>
    </div>
  </f7-page>
</template>
<script>
  import { f7Navbar, f7Page } from 'framework7-vue';

  export default {
    components: {
      f7Navbar,
      f7Page,
    },
  };
</script>
