// kitchen-sink/react/src/pages/tabs-routable.jsx
import React from 'react';
import { Navbar, Page, Block, Tabs, Tab, Link, Toolbar } from 'framework7-react';

export default () => (
  <Page pageContent={false}>
    <Navbar title="Tabs Routable" backLink="返回"></Navbar>
    <Toolbar bottom tabbar>
      <Link tabLink href="./" routeTabId="tab1">Tab 1</Link>
      <Link tabLink href="tab2/" routeTabId="tab2">Tab 2</Link>
      <Link tabLink href="tab3/" routeTabId="tab3">Tab 3</Link>
    </Toolbar>
    <Tabs routable>
      <Tab className="page-content" id="tab1"></Tab>
      <Tab className="page-content" id="tab2"></Tab>
      <Tab className="page-content" id="tab3"></Tab>
    </Tabs>
  </Page>
)

// kitchen-sink/vue/src/pages/tabs-routable.vue
<template>
  <f7-page :page-content="false">
    <f7-navbar title="Tabs Routable" back-link="返回"></f7-navbar>
    <f7-toolbar bottom tabbar>
      <f7-link tab-link href="./" route-tab-id="tab1">Tab 1</f7-link>
      <f7-link tab-link href="tab2/" route-tab-id="tab2">Tab 2</f7-link>
      <f7-link tab-link href="tab3/" route-tab-id="tab3">Tab 3</f7-link>
    </f7-toolbar>
    <f7-tabs routable>
      <f7-tab class="page-content" id="tab1"></f7-tab>
      <f7-tab class="page-content" id="tab2"></f7-tab>
      <f7-tab class="page-content" id="tab3"></f7-tab>
    </f7-tabs>
  </f7-page>
</template>
<script>
  import { f7Navbar, f7Page, f7Block, f7Tabs, f7Tab, f7Link, f7Toolbar } from 'framework7-vue';

  export default {
    components: {
      f7Navbar, f7Page, f7Block, f7Tabs, f7Tab, f7Link, f7Toolbar,
    },
  };
</script>
