// kitchen-sink/react/src/pages/timeline.jsx
import React from 'react';
import { Navbar, Page, List, ListItem } from 'framework7-react';

export default () => (
  <Page>
    <Navbar title="Timeline" backLink="返回"></Navbar>
    <List>
      <ListItem link="/timeline-vertical/" title="Vertical Timeline"></ListItem>
      <ListItem link="/timeline-horizontal/" title="Horizontal Timeline"></ListItem>
      <ListItem link="/timeline-horizontal-calendar/" title="Calendar Timeline"></ListItem>
    </List>
  </Page>
);

// kitchen-sink/vue/src/pages/timeline.vue
<template>
  <f7-page>
    <f7-navbar title="Timeline" back-link="返回"></f7-navbar>
    <f7-list>
      <f7-list-item link="/timeline-vertical/" title="Vertical Timeline"></f7-list-item>
      <f7-list-item link="/timeline-horizontal/" title="Horizontal Timeline"></f7-list-item>
      <f7-list-item link="/timeline-horizontal-calendar/" title="Calendar Timeline"></f7-list-item>
    </f7-list>
  </f7-page>
</template>
<script>
  import { f7Navbar, f7Page, f7List, f7ListItem } from 'framework7-vue';

  export default {
    components: {
      f7Navbar, f7Page, f7List, f7ListItem,
    },
  };
</script>
