// packages/svelte/components/accordion.svelte
<script>
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';
  import restProps from '../utils/rest-props';

  let className = undefined;
  export { className as class };

  export let accordionOpposite = undefined;
  export let accordionHightlight = undefined;

  $: classes = Utils.classNames(
    className,
    'accordion-list',
    accordionOpposite && 'accordion-opposite',
    accordionHightlight && 'accordion-hightlight',
    Mixins.colorClasses($$props),
  );

</script>

<div class={classes} {...restProps($$restProps)}>
  <slot />
</div>

// src/phenome/components/accordion.jsx
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

export default {
  props: {
    id: [String, Number],
    className: String, // phenome-react-line
    style: Object, // phenome-react-line
    accordionOpposite: Boolean,
    accordionHightlight: Boolean,
    ...Mixins.colorProps,
  },
  name: 'f7-accordion',
  render() {
    const props = this.props;
    const {
      className,
      id,
      style,
      accordionOpposite,
      accordionHightlight,
    } = props;
    const classes = Utils.classNames(
      className,
      'accordion-list',
      accordionOpposite && 'accordion-opposite',
      accordionHightlight && 'accordion-hightlight',
      Mixins.colorClasses(props),
    );
    return (
      <div id={id} style={style} className={classes}>
        <slot />
      </div>
    );
  },
};
