// packages/svelte/components/searchbar.svelte
<script>
  import { createEventDispatcher, onMount, onDestroy } from 'svelte';
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';
  import restProps from '../utils/rest-props';
  import f7 from '../utils/f7';

  const dispatch = createEventDispatcher();

  let className = undefined;
  export { className as class };

  export let noShadow = false;
  export let noHairline = false;
  export let form = true;
  export let placeholder = '搜索...';
  export let disableButton = true;
  export let disableButtonText = '取消';
  export let clearButton = true;
  // Input Value
  export let value = undefined;

  // SB Params
  export let inputEvents = 'change input compositionend';
  export let expandable = false;
  export let inline = false;
  export let searchContainer = undefined;
  export let searchIn = '.item-title';
  export let searchItem = 'li';
  export let searchGroup = '.list-group';
  export let searchGroupTitle = '.item-divider, .list-group-title';
  export let foundEl = '.searchbar-found';
  export let notFoundEl = '.searchbar-not-found';
  export let backdrop = undefined;
  export let backdropEl = undefined;
  export let hideOnEnableEl = '.searchbar-hide-on-enable';
  export let hideOnSearchEl = '.searchbar-hide-on-search';
  export let ignore = '.searchbar-ignore';
  export let customSearch = false;
  export let removeDiacritics = false;
  export let hideDividers = true;
  export let hideGroups = true;
  export let init = true;

  export let f7Slot = 'fixed';

  let el;
  let f7Searchbar;

  export function instance() {
    return f7Searchbar;
  }
  export function search(query) {
    if (!f7Searchbar) return undefined;
    return f7Searchbar.search(query);
  }
  export function enable() {
    if (!f7Searchbar) return undefined;
    return f7Searchbar.enable();
  }
  export function disable() {
    if (!f7Searchbar) return undefined;
    return f7Searchbar.disable();
  }
  export function toggle() {
    if (!f7Searchbar) return undefined;
    return f7Searchbar.toggle();
  }
  export function clear() {
    if (!f7Searchbar) return undefined;
    return f7Searchbar.clear();
  }

  $: classes = Utils.classNames(
    className,
    'searchbar',
    {
      'searchbar-inline': inline,
      'no-shadow': noShadow,
      'no-hairline': noHairline,
      'searchbar-expandable': expandable,
    },
    Mixins.colorClasses($$props),
  );

  function onChange(event) {
    dispatch('change', [event]);
    if (typeof $$props.onChange === 'function') $$props.onChange(event);
  }

  function onInput(event) {
    dispatch('input', [event]);
    if (typeof $$props.onInput === 'function') $$props.onInput(event);
  }

  function onFocus(event) {
    dispatch('focus', [event]);
    if (typeof $$props.onFocus === 'function') $$props.onFocus(event);
  }

  function onBlur(event) {
    dispatch('blur', [event]);
    if (typeof $$props.onBlur === 'function') $$props.onBlur(event);
  }

  function onSubmit(event) {
    dispatch('submit', [event]);
    if (typeof $$props.onSubmit === 'function') $$props.onSubmit(event);
  }

  function onClearButtonClick(event) {
    dispatch('click:clear', [event]);
  }

  function onDisableButtonClick(event) {
    dispatch('click:disable', [event]);
  }

  onMount(() => {
    if (!init) return;
    f7.ready(() => {
      const params = Utils.noUndefinedProps({
        el,
        inputEvents,
        searchContainer,
        searchIn,
        searchItem,
        searchGroup,
        searchGroupTitle,
        hideOnEnableEl,
        hideOnSearchEl,
        foundEl,
        notFoundEl,
        backdrop,
        backdropEl,
        disableButton,
        ignore,
        customSearch,
        removeDiacritics,
        hideDividers,
        hideGroups,
        expandable,
        inline,
        on: {
          search(searchbar, query, previousQuery) {
            dispatch('searchbarSearch', [searchbar, query, previousQuery]);
            if (typeof $$props.onSearchbarSearch === 'function') $$props.onSearchbarSearch(searchbar, query, previousQuery);
          },
          clear(searchbar, previousQuery) {
            dispatch('searchbarClear', [searchbar, previousQuery]);
            if (typeof $$props.onSearchbarClear === 'function') $$props.onSearchbarClear(searchbar, previousQuery);
          },
          enable(searchbar) {
            dispatch('searchbarEnable', [searchbar]);
            if (typeof $$props.onSearchbarEnable === 'function') $$props.onSearchbarEnable(searchbar);
          },
          disable(searchbar) {
            dispatch('searchbarDisable', [searchbar]);
            if (typeof $$props.onSearchbarDisable === 'function') $$props.onSearchbarDisable(searchbar);
          },
        },
      });
      Object.keys(params).forEach((key) => {
        if (params[key] === '') {
          delete params[key];
        }
      });
      f7Searchbar = f7.instance.searchbar.create(params);
    });
  });

  onDestroy(() => {
    if (f7Searchbar && f7Searchbar.destroy) {
      f7Searchbar.destroy();
    }
  });
</script>
{#if form}
  <form bind:this={el} class={classes} on:submit={onSubmit} data-f7-slot={f7Slot} {...restProps($$restProps)}>
    <slot name="before-inner" />
    <div class="searchbar-inner">
      <slot name="inner-start" />
      <div class="searchbar-input-wrap">
        <slot name="input-wrap-start" />
        <input
          value={typeof value === 'undefined' ? '' : value}
          placeholder={placeholder}
          type="search"
          on:input={onInput}
          on:change={onChange}
          on:focus={onFocus}
          on:blur={onBlur}
        />
        <i class="searchbar-icon" />
        {#if clearButton}
          <span on:click={onClearButtonClick} class="input-clear-button" />
        {/if}
        <slot name="input-wrap-end" />
      </div>
      {#if disableButton}
        <span on:click={onDisableButtonClick} class="searchbar-disable-button">{disableButtonText}</span>
      {/if}
      <slot name="inner-end" />
      <slot />
    </div>
    <slot name="after-inner" />
  </form>
{:else}
  <div bind:this={el} class={classes} data-f7-slot={f7Slot} {...restProps($$restProps)}>
    <slot name="before-inner" />
    <div class="searchbar-inner">
      <slot name="inner-start" />
      <div class="searchbar-input-wrap">
        <slot name="input-wrap-start" />
        <input
          value={typeof value === 'undefined' ? '' : value}
          placeholder={placeholder}
          type="search"
          on:input={onInput}
          on:change={onChange}
          on:focus={onFocus}
          on:blur={onBlur}
        />
        <i class="searchbar-icon" />
        {#if clearButton}
          <span on:click={onClearButtonClick} class="input-clear-button" />
        {/if}
        <slot name="input-wrap-end" />
      </div>
      {#if disableButton}
        <span on:click={onDisableButtonClick} class="searchbar-disable-button">{disableButtonText}</span>
      {/if}
      <slot name="inner-end" />
      <slot />
    </div>
    <slot name="after-inner" />
  </div>
{/if}

// packages/react/components/searchbar.js
import React from 'react';
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';
import __reactComponentDispatchEvent from '../runtime-helpers/react-component-dispatch-event.js';
import __reactComponentSlots from '../runtime-helpers/react-component-slots.js';
import __reactComponentSetProps from '../runtime-helpers/react-component-set-props.js';

class F7Searchbar extends React.Component {
  constructor(props, context) {
    super(props, context);
    this.__reactRefs = {};

    (() => {
      Utils.bindMethods(this, ['onSubmit', 'onClearButtonClick', 'onDisableButtonClick', 'onInput', 'onChange', 'onFocus', 'onBlur']);
    })();
  }

  search(query) {
    if (!this.f7Searchbar) return undefined;
    return this.f7Searchbar.search(query);
  }

  enable() {
    if (!this.f7Searchbar) return undefined;
    return this.f7Searchbar.enable();
  }

  disable() {
    if (!this.f7Searchbar) return undefined;
    return this.f7Searchbar.disable();
  }

  toggle() {
    if (!this.f7Searchbar) return undefined;
    return this.f7Searchbar.toggle();
  }

  clear() {
    if (!this.f7Searchbar) return undefined;
    return this.f7Searchbar.clear();
  }

  onChange(event) {
    this.dispatchEvent('change', event);
  }

  onInput(event) {
    this.dispatchEvent('input', event);
  }

  onFocus(event) {
    this.dispatchEvent('focus', event);
  }

  onBlur(event) {
    this.dispatchEvent('blur', event);
  }

  onSubmit(event) {
    this.dispatchEvent('submit', event);
  }

  onClearButtonClick(event) {
    this.dispatchEvent('click:clear clickClear', event);
  }

  onDisableButtonClick(event) {
    this.dispatchEvent('click:disable clickDisable', event);
  }

  render() {
    const self = this;
    let clearEl;
    let disableEl;
    const props = self.props;
    const {
      placeholder,
      clearButton,
      disableButton,
      disableButtonText,
      form,
      noShadow,
      noHairline,
      expandable,
      className,
      style,
      id,
      value,
      inline
    } = props;

    if (clearButton) {
      clearEl = React.createElement('span', {
        ref: __reactNode => {
          this.__reactRefs['clearEl'] = __reactNode;
        },
        className: 'input-clear-button'
      });
    }

    if (disableButton) {
      disableEl = React.createElement('span', {
        ref: __reactNode => {
          this.__reactRefs['disableEl'] = __reactNode;
        },
        className: 'searchbar-disable-button'
      }, disableButtonText);
    }

    const SearchbarTag = form ? 'form' : 'div';
    const classes = Utils.classNames(className, 'searchbar', {
      'searchbar-inline': inline,
      'no-shadow': noShadow,
      'no-hairline': noHairline,
      'searchbar-expandable': expandable
    }, Mixins.colorClasses(props));
    let inputEl;
    {
      inputEl = React.createElement('input', {
        ref: __reactNode => {
          this.__reactRefs['inputEl'] = __reactNode;
        },
        value: value,
        placeholder: placeholder,
        type: 'search',
        onInput: self.onInput,
        onChange: self.onChange.bind(self),
        onFocus: self.onFocus,
        onBlur: self.onBlur
      });
    }
    return React.createElement(SearchbarTag, {
      ref: __reactNode => {
        this.__reactRefs['el'] = __reactNode;
      },
      id: id,
      style: style,
      className: classes
    }, this.slots['before-inner'], React.createElement('div', {
      className: 'searchbar-inner'
    }, this.slots['inner-start'], React.createElement('div', {
      className: 'searchbar-input-wrap'
    }, this.slots['input-wrap-start'], inputEl, React.createElement('i', {
      className: 'searchbar-icon'
    }), clearEl, this.slots['input-wrap-end']), disableEl, this.slots['inner-end'], this.slots['default']), this.slots['after-inner']);
  }

  componentWillUnmount() {
    const self = this;
    const {
      el,
      clearEl,
      disableEl
    } = self.refs;

    if (self.props.form && el) {
      el.removeEventListener('submit', self.onSubmit, false);
    }

    if (clearEl) {
      clearEl.removeEventListener('click', self.onClearButtonClick);
    }

    if (disableEl) {
      disableEl.removeEventListener('click', self.onDisableButtonClick);
    }

    if (self.f7Searchbar && self.f7Searchbar.destroy) self.f7Searchbar.destroy();
  }

  componentDidMount() {
    const self = this;
    const {
      init,
      inputEvents,
      searchContainer,
      searchIn,
      searchItem,
      searchGroup,
      searchGroupTitle,
      hideOnEnableEl,
      hideOnSearchEl,
      foundEl,
      notFoundEl,
      backdrop,
      backdropEl,
      disableButton,
      ignore,
      customSearch,
      removeDiacritics,
      hideDividers,
      hideGroups,
      form,
      expandable,
      inline
    } = self.props;
    const {
      el,
      clearEl,
      disableEl
    } = self.refs;

    if (form && el) {
      el.addEventListener('submit', self.onSubmit, false);
    }

    if (clearEl) {
      clearEl.addEventListener('click', self.onClearButtonClick);
    }

    if (disableEl) {
      disableEl.addEventListener('click', self.onDisableButtonClick);
    }

    if (!init) return;
    self.$f7ready(() => {
      const params = Utils.noUndefinedProps({
        el: self.refs.el,
        inputEvents,
        searchContainer,
        searchIn,
        searchItem,
        searchGroup,
        searchGroupTitle,
        hideOnEnableEl,
        hideOnSearchEl,
        foundEl,
        notFoundEl,
        backdrop,
        backdropEl,
        disableButton,
        ignore,
        customSearch,
        removeDiacritics,
        hideDividers,
        hideGroups,
        expandable,
        inline,
        on: {
          search(searchbar, query, previousQuery) {
            self.dispatchEvent('searchbar:search searchbarSearch', searchbar, query, previousQuery);
          },

          clear(searchbar, previousQuery) {
            self.dispatchEvent('searchbar:clear searchbarClear', searchbar, previousQuery);
          },

          enable(searchbar) {
            self.dispatchEvent('searchbar:enable searchbarEnable', searchbar);
          },

          disable(searchbar) {
            self.dispatchEvent('searchbar:disable searchbarDisable', searchbar);
          }

        }
      });
      Object.keys(params).forEach(key => {
        if (params[key] === '') {
          delete params[key];
        }
      });
      self.f7Searchbar = self.$f7.searchbar.create(params);
    });
  }

  get slots() {
    return __reactComponentSlots(this.props);
  }

  dispatchEvent(events, ...args) {
    return __reactComponentDispatchEvent(this, events, ...args);
  }

  get refs() {
    return this.__reactRefs;
  }

  set refs(refs) {}

}

__reactComponentSetProps(F7Searchbar, Object.assign({
  id: [String, Number],
  className: String,
  style: Object,
  noShadow: Boolean,
  noHairline: Boolean,
  form: {
    type: Boolean,
    default: true
  },
  placeholder: {
    type: String,
    default: '搜索...'
  },
  disableButton: {
    type: Boolean,
    default: true
  },
  disableButtonText: {
    type: String,
    default: '取消'
  },
  clearButton: {
    type: Boolean,
    default: true
  },
  value: [String, Number, Array],
  inputEvents: {
    type: String,
    default: 'change input compositionend'
  },
  expandable: Boolean,
  inline: Boolean,
  searchContainer: [String, Object],
  searchIn: {
    type: String,
    default: '.item-title'
  },
  searchItem: {
    type: String,
    default: 'li'
  },
  searchGroup: {
    type: String,
    default: '.list-group'
  },
  searchGroupTitle: {
    type: String,
    default: '.item-divider, .list-group-title'
  },
  foundEl: {
    type: [String, Object],
    default: '.searchbar-found'
  },
  notFoundEl: {
    type: [String, Object],
    default: '.searchbar-not-found'
  },
  backdrop: {
    type: Boolean,
    default: undefined
  },
  backdropEl: [String, Object],
  hideOnEnableEl: {
    type: [String, Object],
    default: '.searchbar-hide-on-enable'
  },
  hideOnSearchEl: {
    type: [String, Object],
    default: '.searchbar-hide-on-search'
  },
  ignore: {
    type: String,
    default: '.searchbar-ignore'
  },
  customSearch: {
    type: Boolean,
    default: false
  },
  removeDiacritics: {
    type: Boolean,
    default: false
  },
  hideDividers: {
    type: Boolean,
    default: true
  },
  hideGroups: {
    type: Boolean,
    default: true
  },
  init: {
    type: Boolean,
    default: true
  }
}, Mixins.colorProps));

F7Searchbar.displayName = 'f7-searchbar';
export default F7Searchbar;
