// packages/react/components/accordion.js
import React from 'react';
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';
import __reactComponentSlots from '../runtime-helpers/react-component-slots.js';
import __reactComponentSetProps from '../runtime-helpers/react-component-set-props.js';

class F7Accordion extends React.Component {
  constructor(props, context) {
    super(props, context);
  }

  render() {
    const props = this.props;
    const {
      className,
      id,
      style,
      accordionOpposite,
      accordionHightlight
    } = props;
    const classes = Utils.classNames(className, 'accordion-list', accordionOpposite && 'accordion-opposite', accordionHightlight && 'accordion-hightlight', Mixins.colorClasses(props));
    return React.createElement('div', {
      id: id,
      style: style,
      className: classes
    }, this.slots['default']);
  }

  get slots() {
    return __reactComponentSlots(this.props);
  }

}

__reactComponentSetProps(F7Accordion, Object.assign({
  id: [String, Number],
  className: String,
  style: Object,
  accordionOpposite: Boolean,
  accordionHightlight: Boolean
}, Mixins.colorProps));

F7Accordion.displayName = 'f7-accordion';
export default F7Accordion;

// packages/svelte/components/accordion.svelte
<script>
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';
  import restProps from '../utils/rest-props';

  let className = undefined;
  export { className as class };

  export let accordionOpposite = undefined;
  export let accordionHightlight = undefined;

  $: classes = Utils.classNames(
    className,
    'accordion-list',
    accordionOpposite && 'accordion-opposite',
    accordionHightlight && 'accordion-hightlight',
    Mixins.colorClasses($$props),
  );

</script>

<div class={classes} {...restProps($$restProps)}>
  <slot />
</div>
