// kitchen-sink/vue/src/pages/buttons.vue
<template>
  <f7-page>
    <f7-navbar title="Buttons" back-link="返回"></f7-navbar>

    <f7-block-title>Usual Buttons</f7-block-title>
    <f7-block strong>
      <f7-row>
        <f7-col>
          <f7-button>Button</f7-button>
        </f7-col>
        <f7-col>
          <f7-button round>Round</f7-button>
        </f7-col>
        <f7-col>
          <f7-button rectangle>Rectangle</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Fill Buttons</f7-block-title>
    <f7-block strong>
      <f7-row>
        <f7-col>
          <f7-button fill>Button</f7-button>
        </f7-col>
        <f7-col>
          <f7-button fill round>Round</f7-button>
        </f7-col>
        <f7-col>
          <f7-button fill rectangle>Rectangle</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Outline Buttons</f7-block-title>
    <f7-block strong>
      <f7-row>
        <f7-col>
          <f7-button outline>Button</f7-button>
        </f7-col>
        <f7-col>
          <f7-button outline round>Round</f7-button>
        </f7-col>
        <f7-col>
          <f7-button outline rectangle>Rectangle</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Raised Buttons</f7-block-title>
    <f7-block strong>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button raised>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button raised fill>Fill</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button raised outline>Outline</f7-button>
        </f7-col>
      </f7-row>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button raised round>Round</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button raised fill round>Fill</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button raised outline round>Outline</f7-button>
        </f7-col>
      </f7-row>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button raised rectangle>Rectangle</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button raised fill rectangle>Fill</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button raised outline rectangle>Outline</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Segmented</f7-block-title>
    <f7-block strong>
       <f7-segmented tag="p">
        <f7-button>Button</f7-button>
        <f7-button>Button</f7-button>
        <f7-button active>Active</f7-button>
      </f7-segmented>
      <f7-segmented strong tag="p">
        <f7-button :active="activeStrongButton === 0" @click="activeStrongButton = 0">Button</f7-button>
        <f7-button :active="activeStrongButton === 1" @click="activeStrongButton = 1">Button</f7-button>
        <f7-button :active="activeStrongButton === 2" @click="activeStrongButton = 2">Button</f7-button>
      </f7-segmented>
      <f7-segmented raised tag="p">
        <f7-button>Button</f7-button>
        <f7-button>Button</f7-button>
        <f7-button active>Active</f7-button>
      </f7-segmented>
      <f7-segmented tag="p">
        <f7-button outline>Outline</f7-button>
        <f7-button outline>Outline</f7-button>
        <f7-button outline active>Active</f7-button>
      </f7-segmented>
      <f7-segmented raised round tag="p">
        <f7-button round>Button</f7-button>
        <f7-button round>Button</f7-button>
        <f7-button round active>Active</f7-button>
      </f7-segmented>
      <f7-segmented raised rectangle tag="p">
        <f7-button rectangle>Button</f7-button>
        <f7-button rectangle>Button</f7-button>
        <f7-button rectangle active>Active</f7-button>
      </f7-segmented>
      <f7-segmented round tag="p">
        <f7-button round outline>Outline</f7-button>
        <f7-button round outline>Outline</f7-button>
        <f7-button round outline active>Active</f7-button>
      </f7-segmented>
      <f7-segmented rectangle tag="p">
        <f7-button rectangle outline>Outline</f7-button>
        <f7-button rectangle outline>Outline</f7-button>
        <f7-button rectangle outline active>Active</f7-button>
      </f7-segmented>
    </f7-block>

    <f7-block-title>Large Buttons</f7-block-title>
    <f7-block strong>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button large>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button large outline>Outline</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button large fill>Fill</f7-button>
        </f7-col>
      </f7-row>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button large raised>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button large raised outline>Outline</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button large raised fill>Fill</f7-button>
        </f7-col>
      </f7-row>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button large round>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button large outline round>Outline</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button large fill round>Fill</f7-button>
        </f7-col>
      </f7-row>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button large rectangle>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button large outline rectangle>Outline</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button large fill rectangle>Fill</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Small Buttons</f7-block-title>
    <f7-block strong>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button small>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button small outline>Outline</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button small fill>Fill</f7-button>
        </f7-col>
      </f7-row>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button small raised>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button small raised outline>Outline</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button small raised fill>Fill</f7-button>
        </f7-col>
      </f7-row>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button small round>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button small outline round>Outline</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button small fill round>Fill</f7-button>
        </f7-col>
      </f7-row>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button small rectangle>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button small outline rectangle>Outline</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button small fill rectangle>Fill</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Color Buttons</f7-block-title>
    <f7-block strong>
      <f7-row>
        <f7-col>
          <f7-button color="red">Red</f7-button>
        </f7-col>
        <f7-col>
          <f7-button color="green">Green</f7-button>
        </f7-col>
        <f7-col>
          <f7-button color="blue">Blue</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Color Fill Buttons</f7-block-title>
    <f7-block strong>
      <f7-row>
        <f7-col>
          <f7-button fill color="red">Red</f7-button>
        </f7-col>
        <f7-col>
          <f7-button fill color="green">Green</f7-button>
        </f7-col>
        <f7-col>
          <f7-button fill color="blue">Blue</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>List-Block Buttons</f7-block-title>
    <f7-list inset>
      <f7-list-button title="List Button 1"></f7-list-button>
      <f7-list-button title="List Button 2"></f7-list-button>
      <f7-list-button title="List Button 3"></f7-list-button>
    </f7-list>
    <f7-list inset>
      <f7-list-button title="Large Red Button" color="red"></f7-list-button>
    </f7-list>
  </f7-page>
</template>
<script>
  import { f7Navbar, f7Page, f7BlockTitle, f7Block, f7List, f7Row, f7Col, f7ListButton, f7Button, f7Segmented } from 'framework7-vue';

  export default {
    components: {
      f7Navbar,
      f7Page,
      f7BlockTitle,
      f7Block,
      f7List,
      f7Row,
      f7Col,
      f7ListButton,
      f7Button,
      f7Segmented,
    },
    data() {
      return {
        activeStrongButton: 0,
      };
    },
  }
</script>

// kitchen-sink/react/src/pages/buttons.jsx
import React from 'react';
import { Navbar, Page, BlockTitle, Block, List, Row, Col, ListButton, Button, Segmented } from 'framework7-react';

export default class extends React.Component {
  constructor(){
    super();
    this.state = {
      activeStrongButton: 0
    }
  }
  render() {
    return (
      <Page>
        <Navbar title="Buttons" backLink="返回" />

        <BlockTitle>Usual Buttons</BlockTitle>
        <Block strong>
          <Row>
            <Col>
              <Button>Button</Button>
            </Col>
            <Col>
              <Button round>Round</Button>
            </Col>
            <Col>
              <Button rectangle>Rectangle</Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Fill Buttons</BlockTitle>
        <Block strong>
          <Row>
            <Col>
              <Button fill>Button</Button>
            </Col>
            <Col>
              <Button fill round>Round</Button>
            </Col>
            <Col>
              <Button fill rectangle>Rectangle</Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Outline Buttons</BlockTitle>
        <Block strong>
          <Row>
            <Col>
              <Button outline>Button</Button>
            </Col>
            <Col>
              <Button outline round>Round</Button>
            </Col>
            <Col>
              <Button outline rectangle>Rectangle</Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Raised Buttons</BlockTitle>
        <Block strong>
          <Row tag="p">
            <Col tag="span">
              <Button raised>Button</Button>
            </Col>
            <Col tag="span">
              <Button raised fill>Fill</Button>
            </Col>
            <Col tag="span">
              <Button raised outline>Outline</Button>
            </Col>
          </Row>
          <Row tag="p">
            <Col tag="span">
              <Button raised round>Round</Button>
            </Col>
            <Col tag="span">
              <Button raised fill round>Fill</Button>
            </Col>
            <Col tag="span">
              <Button raised outline round>Outline</Button>
            </Col>
          </Row>
          <Row tag="p">
            <Col tag="span">
              <Button raised rectangle>Rectangle</Button>
            </Col>
            <Col tag="span">
              <Button raised fill rectangle>Fill</Button>
            </Col>
            <Col tag="span">
              <Button raised outline rectangle>Outline</Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Segmented</BlockTitle>
        <Block strong>
          <Segmented tag="p">
            <Button>Button</Button>
            <Button>Button</Button>
            <Button active>Active</Button>
          </Segmented>
          <Segmented strong tag="p">
            <Button
              active={this.state.activeStrongButton === 0}
              onClick={() => this.setState({ activeStrongButton: 0 })}
            >Button</Button>
            <Button
              active={this.state.activeStrongButton === 1}
              onClick={() => this.setState({ activeStrongButton: 1 })}
            >Button</Button>
            <Button
              active={this.state.activeStrongButton === 2}
              onClick={() => this.setState({ activeStrongButton: 2 })}
            >Button</Button>
          </Segmented>
          <Segmented raised tag="p">
            <Button>Button</Button>
            <Button>Button</Button>
            <Button active>Active</Button>
          </Segmented>
          <Segmented tag="p">
            <Button outline>Outline</Button>
            <Button outline>Outline</Button>
            <Button outline active>Active</Button>
          </Segmented>
          <Segmented raised round tag="p">
            <Button round>Button</Button>
            <Button round>Button</Button>
            <Button round active>Active</Button>
          </Segmented>
          <Segmented raised rectangle tag="p">
            <Button rectangle>Button</Button>
            <Button rectangle>Button</Button>
            <Button rectangle active>Active</Button>
          </Segmented>
          <Segmented round tag="p">
            <Button round outline>Outline</Button>
            <Button round outline>Outline</Button>
            <Button round outline active>Active</Button>
          </Segmented>
          <Segmented rectangle tag="p">
            <Button rectangle outline>Outline</Button>
            <Button rectangle outline>Outline</Button>
            <Button rectangle outline active>Active</Button>
          </Segmented>
        </Block>

        <BlockTitle>Large Buttons</BlockTitle>
        <Block strong>
        <Row tag="p">
            <Col tag="span">
              <Button small>Button</Button>
            </Col>
            <Col tag="span">
              <Button small outline>Outline</Button>
            </Col>
            <Col tag="span">
              <Button small fill>Fill</Button>
            </Col>
          </Row>
          <Row tag="p">
            <Col tag="span">
              <Button small raised>Button</Button>
            </Col>
            <Col tag="span">
              <Button small outline raised>Outline</Button>
            </Col>
            <Col tag="span">
              <Button small fill raised>Fill</Button>
            </Col>
          </Row>   
          <Row tag="p">
            <Col tag="span">
              <Button small round>Button</Button>
            </Col>
            <Col tag="span">
              <Button small outline round>Outline</Button>
            </Col>
            <Col tag="span">
              <Button small fill round>Fill</Button>
            </Col>
          </Row>
          <Row tag="p">
            <Col tag="span">
              <Button small rectangle>Button</Button>
            </Col>
            <Col tag="span">
              <Button small outline rectangle>Outline</Button>
            </Col>
            <Col tag="span">
              <Button small fill rectangle>Fill</Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Small Buttons</BlockTitle>
        <Block strong>
          <Row tag="p">
            <Col tag="span">
              <Button small>Button</Button>
            </Col>
            <Col tag="span">
              <Button small outline>Outline</Button>
            </Col>
            <Col tag="span">
              <Button small fill>Fill</Button>
            </Col>
          </Row>
          <Row tag="p">
            <Col tag="span">
              <Button small raised>Button</Button>
            </Col>
            <Col tag="span">
              <Button small outline raised>Outline</Button>
            </Col>
            <Col tag="span">
              <Button small fill raised>Fill</Button>
            </Col>
          </Row>   
          <Row tag="p">
            <Col tag="span">
              <Button small round>Button</Button>
            </Col>
            <Col tag="span">
              <Button small outline round>Outline</Button>
            </Col>
            <Col tag="span">
              <Button small fill round>Fill</Button>
            </Col>
          </Row>
          <Row tag="p">
            <Col tag="span">
              <Button small rectangle>Button</Button>
            </Col>
            <Col tag="span">
              <Button small outline rectangle>Outline</Button>
            </Col>
            <Col tag="span">
              <Button small fill rectangle>Fill</Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Color Buttons</BlockTitle>
        <Block strong>
          <Row>
            <Col>
              <Button color="red">Red</Button>
            </Col>
            <Col>
              <Button color="green">Green</Button>
            </Col>
            <Col>
              <Button color="blue">Blue</Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>Color Fill Buttons</BlockTitle>
        <Block strong>
          <Row>
            <Col>
              <Button fill color="red">Red</Button>
            </Col>
            <Col>
              <Button fill color="green">Green</Button>
            </Col>
            <Col>
              <Button fill color="blue">Blue</Button>
            </Col>
          </Row>
        </Block>

        <BlockTitle>List-Block Buttons</BlockTitle>
        <List inset>
          <ListButton title="List Button 1"></ListButton>
          <ListButton title="List Button 2"></ListButton>
          <ListButton title="List Button 3"></ListButton>
        </List>
        <List inset>
          <ListButton title="Large Red Button" color="red"></ListButton>
        </List>
      </Page>
    );
  }
}
