// kitchen-sink/svelte/src/pages/navbar.svelte
<Page>
  <Navbar title="Navbar" subtitle="Subtitle" backLink="返回">
    <NavRight>
      <Link>Right</Link>
    </NavRight>
  </Navbar>
  <Block>
    <p>Navbar is a fixed (with Fixed and Through layout types) area at the top of a screen that contains Page title and navigation elements.</p>
    <p>Navbar has 3 main parts: Left, Title and Right. Each part may contain any HTML content.</p>
  </Block>
  <List>
    <ListItem link="/navbar-hide-scroll/" title="Hide Navbar On Scroll"></ListItem>
  </List>
</Page>
<script>
  import { Navbar, Page, Block, List, ListItem, NavRight, Link } from 'framework7-svelte';
</script>

// kitchen-sink/react/src/pages/navbar.jsx
import React from 'react';
import { Navbar, Page, Block, List, ListItem, NavRight, Link } from 'framework7-react';

export default () => (
  <Page>
    <Navbar title="Navbar" subtitle="Subtitle" backLink="返回">
      <NavRight>
        <Link>Right</Link>
      </NavRight>
    </Navbar>
    <Block>
      <p>Navbar is a fixed (with Fixed and Through layout types) area at the top of a screen that contains Page title and navigation elements.</p>
      <p>Navbar has 3 main parts: Left, Title and Right. Each part may contain any HTML content.</p>
    </Block>
    <List>
      <ListItem link="/navbar-hide-scroll/" title="Hide Navbar On Scroll"></ListItem>
    </List>
  </Page>
);
