// kitchen-sink/svelte/src/pages/photo-browser.svelte
<Page>
  <Navbar title="Photo Browser" backLink="返回"></Navbar>
  <Block strong>
    <p>Photo Browser is a standalone and highly configurable component that allows to open window with photo viewer and navigation elements with the following features:</p>
    <ul>
      <li>Swiper between photos</li>
      <li>Multi-gestures support for zooming</li>
      <li>Toggle zoom by double tap on photo</li>
      <li>Single click on photo to toggle Exposition mode</li>
    </ul>
  </Block>
  <Block strong>
    <p>Photo Browser could be opened in a three ways - as a Standalone component (Popup modification), in Popup, and as separate Page:</p>
    <Row>
      <Col>
        <PhotoBrowser photos={photos} bind:this={ standalone } />
        <Button fill onClick={() => standalone.open()}>Standalone</Button>
      </Col>
      <Col>
        <PhotoBrowser photos={photos} type="popup" bind:this={ popup } />
        <Button fill onClick={() => popup.open()}>Popup</Button>
      </Col>
      <Col>
        <PhotoBrowser photos={photos} type="page" pageBackLinkText="返回" bind:this={ page } />
        <Button fill onClick={() => page.open()}>Page</Button>
      </Col>
    </Row>
  </Block>
  <Block strong>
    <p>Photo Browser suppots 2 default themes - default Light (like in previous examples) and Dark theme. Here is a Dark theme examples:</p>
    <Row>
      <Col>
        <PhotoBrowser photos={photos} theme="dark" bind:this={ standaloneDark } />
        <Button fill onClick={() => standaloneDark.open()}>Standalone</Button>
      </Col>
      <Col>
        <PhotoBrowser photos={photos} theme="dark" type="popup" bind:this={ popupDark } />
        <Button fill onClick={() => popupDark.open()}>Popup</Button>
      </Col>
      <Col>
        <PhotoBrowser photos={photos} theme="dark" type="page" pageBackLinkText="返回" bind:this={ pageDark } />
        <Button fill onClick={() => pageDark.open()}>Page</Button>
      </Col>
    </Row>
  </Block>
</Page>
<script>
  import { Navbar, Page, PhotoBrowser, Block, Row, Col, Button } from 'framework7-svelte';

  let standalone;
  let popup;
  let page;

  let standaloneDark;
  let popupDark;
  let pageDark;

  let photos = [
    {
      url: 'img/beach.jpg',
      caption: 'Amazing beach in Goa, India',
    },
    'http://placekitten.com/1024/1024',
    'img/lock.jpg',
    {
      url: 'img/monkey.jpg',
      caption: 'I met this monkey in Chinese mountains',
    },
    {
      url: 'img/mountains.jpg',
      caption: 'Beautiful mountains in Zhangjiajie, China',
    },
  ];
</script>

// kitchen-sink/react/src/pages/photo-browser.jsx
import React from 'react';
import { Navbar, Page, PhotoBrowser, Block, Row, Col, Button } from 'framework7-react';

export default class extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      photos: [
        {
          url: 'img/beach.jpg',
          caption: 'Amazing beach in Goa, India',
        },
        'http://placekitten.com/1024/1024',
        'img/lock.jpg',
        {
          url: 'img/monkey.jpg',
          caption: 'I met this monkey in Chinese mountains',
        },
        {
          url: 'img/mountains.jpg',
          caption: 'Beautiful mountains in Zhangjiajie, China',
        },
      ],
    }
  }
  render() {
    return (
      <Page>
        <Navbar title="Photo Browser" backLink="返回"></Navbar>
        <Block strong>
          <p>Photo Browser is a standalone and highly configurable component that allows to open window with photo viewer and navigation elements with the following features:</p>
          <ul>
            <li>Swiper between photos</li>
            <li>Multi-gestures support for zooming</li>
            <li>Toggle zoom by double tap on photo</li>
            <li>Single click on photo to toggle Exposition mode</li>
          </ul>
        </Block>
        <Block strong>
          <p>Photo Browser could be opened in a three ways - as a Standalone component (Popup modification), in Popup, and as separate Page:</p>
          <Row>
            <Col>
              <PhotoBrowser photos={this.state.photos} ref={(el) => {this.standalone = el}} />
              <Button fill onClick={() => this.standalone.open()}>Standalone</Button>
            </Col>
            <Col>
              <PhotoBrowser photos={this.state.photos} type="popup" ref={(el) => {this.popup = el}} />
              <Button fill onClick={() => this.popup.open()}>Popup</Button>
            </Col>
            <Col>
              <PhotoBrowser photos={this.state.photos} type="page" pageBackLinkText="返回" ref={(el) => {this.page = el}} />
              <Button fill onClick={() => this.page.open()}>Page</Button>
            </Col>
          </Row>
        </Block>
        <Block strong>
          <p>Photo Browser suppots 2 default themes - default Light (like in previous examples) and Dark theme. Here is a Dark theme examples:</p>
          <Row>
            <Col>
              <PhotoBrowser photos={this.state.photos} theme="dark" ref={(el) => {this.standaloneDark = el}} />
              <Button fill onClick={() => this.standaloneDark.open()}>Standalone</Button>
            </Col>
            <Col>
              <PhotoBrowser photos={this.state.photos} theme="dark" type="popup" ref={(el) => {this.popupDark = el}} />
              <Button fill onClick={() => this.popupDark.open()}>Popup</Button>
            </Col>
            <Col>
              <PhotoBrowser photos={this.state.photos} theme="dark" type="page" pageBackLinkText="返回" ref={(el) => {this.pageDark = el}} />
              <Button fill onClick={() => this.pageDark.open()}>Page</Button>
            </Col>
          </Row>
        </Block>
      </Page>
    );
  }
};
