// kitchen-sink/svelte/src/pages/routable-modals.svelte
<Page>
  <Navbar title="Routable Modals" backLink="返回"></Navbar>
  <Block strong>
    <p>In addition to pages, Framework7 router allows to load modal components:</p>
  </Block>
  <List>
    <ListItem title="Popup" link="popup/"></ListItem>
    <ListItem title="Action Sheet" link="actions/"></ListItem>
  </List>
</Page>
<script>
  import { Navbar, Page, List, ListItem, Block } from 'framework7-svelte';
</script>

// kitchen-sink/react/src/pages/routable-modals.jsx
import React from 'react';
import { Navbar, Page, List, ListItem, Block } from 'framework7-react';

export default () => (
  <Page>
    <Navbar title="Routable Modals" backLink="返回"></Navbar>
    <Block strong>
      <p>In addition to pages, Framework7 router allows to load modal components:</p>
    </Block>
    <List>
      <ListItem title="Popup" link="popup/"></ListItem>
      <ListItem title="Action Sheet" link="actions/"></ListItem>
    </List>
  </Page>
);
