// kitchen-sink/svelte/src/pages/routable-popup.svelte
<Popup>
  <Page>
    <Navbar title="Routable Popup">
      <NavRight>
        <Link popupClose>关闭</Link>
      </NavRight>
    </Navbar>
    <Block strong>
      <p>This Popup was loaded using route link as standalone component</p>
      <p>滚滚长江东逝水，浪花淘尽英雄。是非成败转头空，青山依旧在，几度夕阳红。白发渔樵江渚上，惯看秋月春风。一壶浊酒喜相逢，古今多少事，都付笑谈中。</p>
      <p>滚滚长江东逝水，浪花淘尽英雄。是非成败转头空，青山依旧在，几度夕阳红。白发渔樵江渚上，惯看秋月春风。一壶浊酒喜相逢，古今多少事，都付笑谈中。</p>
    </Block>
  </Page>
</Popup>
<script>
  import { Popup, Navbar, NavRight, Link, Page, List, ListItem, Block } from 'framework7-svelte';
</script>

// kitchen-sink/react/src/pages/routable-popup.jsx
import React from 'react';
import { Popup, Navbar, NavRight, Link, Page, List, ListItem, Block } from 'framework7-react';

export default () => (
  <Popup>
    <Page>
      <Navbar title="Routable Popup">
        <NavRight>
          <Link popupClose>关闭</Link>
        </NavRight>
      </Navbar>
      <Block strong>
        <p>This Popup was loaded using route link as standalone component</p>
        <p>滚滚长江东逝水，浪花淘尽英雄。是非成败转头空，青山依旧在，几度夕阳红。白发渔樵江渚上，惯看秋月春风。一壶浊酒喜相逢，古今多少事，都付笑谈中。</p>
        <p>滚滚长江东逝水，浪花淘尽英雄。是非成败转头空，青山依旧在，几度夕阳红。白发渔樵江渚上，惯看秋月春风。一壶浊酒喜相逢，古今多少事，都付笑谈中。</p>
      </Block>
    </Page>
  </Popup>
)
