// kitchen-sink/svelte/src/pages/routable-actions.svelte
<Actions>
  <ActionsGroup>
    <ActionsLabel>This Action Sheet was loaded as standalone component</ActionsLabel>
    <ActionsButton>Action 1</ActionsButton>
    <ActionsButton>Action 2</ActionsButton>
  </ActionsGroup>
  <ActionsGroup>
    <ActionsButton color="red">取消</ActionsButton>
  </ActionsGroup>
</Actions>
<script>
  import { Actions, ActionsLabel, ActionsGroup, ActionsButton } from 'framework7-svelte';
</script>

// kitchen-sink/react/src/pages/routable-actions.jsx
import React from 'react';
import { Actions, ActionsLabel, ActionsGroup, ActionsButton } from 'framework7-react';

export default () => (
  <Actions>
    <ActionsGroup>
      <ActionsLabel>This Action Sheet was loaded as standalone component</ActionsLabel>
      <ActionsButton>Action 1</ActionsButton>
      <ActionsButton>Action 2</ActionsButton>
    </ActionsGroup>
    <ActionsGroup>
      <ActionsButton color="red">取消</ActionsButton>
    </ActionsGroup>
  </Actions>
);
