// kitchen-sink/vue/src/pages/routable-modals.vue
<template>
  <f7-page>
    <f7-navbar title="Routable Modals" backLink="返回"></f7-navbar>
    <f7-block>
      <p>In addition to pages, Framework7 router allows to load modal components:</p>
    </f7-block>
    <f7-list>
      <f7-list-item title="Popup" link="popup/"></f7-list-item>
      <f7-list-item title="Action Sheet" link="actions/"></f7-list-item>
    </f7-list>
  </f7-page>
</template>
<script>
  import { f7Navbar, f7Page, f7List, f7ListItem, f7Block } from 'framework7-vue';

  export default {
    components: {
      f7Navbar, f7Page, f7List, f7ListItem, f7Block
    },
  };
</script>

// kitchen-sink/react/src/pages/routable-modals.jsx
import React from 'react';
import { Navbar, Page, List, ListItem, Block } from 'framework7-react';

export default () => (
  <Page>
    <Navbar title="Routable Modals" backLink="返回"></Navbar>
    <Block strong>
      <p>In addition to pages, Framework7 router allows to load modal components:</p>
    </Block>
    <List>
      <ListItem title="Popup" link="popup/"></ListItem>
      <ListItem title="Action Sheet" link="actions/"></ListItem>
    </List>
  </Page>
);
