// kitchen-sink/svelte/src/pages/timeline.svelte
<Page>
  <Navbar title="Timeline" backLink="返回"></Navbar>
  <List>
    <ListItem link="/timeline-vertical/" title="Vertical Timeline"></ListItem>
    <ListItem link="/timeline-horizontal/" title="Horizontal Timeline"></ListItem>
    <ListItem link="/timeline-horizontal-calendar/" title="Calendar Timeline"></ListItem>
  </List>
</Page>
<script>
  import { Navbar, Page, List, ListItem } from 'framework7-svelte';
</script>

// kitchen-sink/react/src/pages/timeline.jsx
import React from 'react';
import { Navbar, Page, List, ListItem } from 'framework7-react';

export default () => (
  <Page>
    <Navbar title="Timeline" backLink="返回"></Navbar>
    <List>
      <ListItem link="/timeline-vertical/" title="Vertical Timeline"></ListItem>
      <ListItem link="/timeline-horizontal/" title="Horizontal Timeline"></ListItem>
      <ListItem link="/timeline-horizontal-calendar/" title="Calendar Timeline"></ListItem>
    </List>
  </Page>
);
