// kitchen-sink/svelte/src/pages/toast.svelte
<Page onPageBeforeRemove={onPageBeforeRemove} onPageBeforeOut={onPageBeforeOut}>
  <Navbar title="Toast" backLink="返回"></Navbar>
  <Block strong>
    <p>Toasts provide brief feedback about an operation through a message on the screen.</p>
    <p>
      <Button fill onClick={showToastBottom}>Toast on Bottom</Button>
    </p>
    <p>
      <Button fill onClick={showToastTop}>Toast on Top</Button>
    </p>
    <p>
      <Button fill onClick={showToastCenter}>Toast on Center</Button>
    </p>
    <p>
      <Button fill onClick={showToastIcon}>Toast with icon</Button>
    </p>
    <p>
      <Button fill onClick={showToastLargeMessage}>Toast with large message</Button>
    </p>
    <p>
      <Button fill onClick={showToastWithButton}>Toast with close button</Button>
    </p>
    <p>
      <Button fill onClick={showToastWithCustomButton}>Toast with custom button</Button>
    </p>
    <p>
      <Button fill onClick={showToastWithCallback}>Toast with callback on close</Button>
    </p>
  </Block>
</Page>
<script>
  import { f7, theme, Navbar, Page, Block, Button } from 'framework7-svelte';

  let toastBottom;
  let toastTop;
  let toastCenter;
  let toastIcon;
  let toastLargeMessage;
  let toastWithButton;
  let toastWithCustomButton;
  let toastWithCallback;

  function showToastBottom() {
    // Create toast
    if (toastBottom) {
      toastBottom = f7.toast.create({
        text: 'This is default bottom positioned toast',
        closeTimeout: 2000,
      });
    }
    // Open it
    toastBottom.open();
  }
  function showToastTop() {
    // Create toast
    if (!toastTop) {
      toastTop = f7.toast.create({
        text: 'Top positioned toast',
        position: 'top',
        closeTimeout: 2000,
      });
    }
    // Open it
    toastTop.open();
  }
  function showToastCenter() {
    // Create toast
    if (!toastCenter) {
      toastCenter = f7.toast.create({
        text: 'I\'m on center',
        position: 'center',
        closeTimeout: 2000,
      });
    }
    // Open it
    toastCenter.open();
  }
  function showToastIcon() {
    // Create toast
    if (!toastIcon) {
      toastIcon = f7.toast.create({
        icon: theme.ios || theme.aurora ? '<i class="f7-icons">star_fill</i>' : '<i class="material-icons">star</i>',
        text: 'I\'m on center',
        position: 'center',
        closeTimeout: 2000,
      });
    }
    // Open it
    toastIcon.open();
  }
  function showToastLargeMessage() {
    // Create toast
    if (!toastLargeMessage) {
      toastLargeMessage = f7.toast.create({
        text: 'This toast contains a lot of text. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil, quae, ab. Delectus amet optio facere autem sapiente quisquam beatae culpa dolore.',
        closeTimeout: 2000,
      });
    }
    // Open it
    toastLargeMessage.open();
  }
  function showToastWithButton() {
    // Create toast
    if (!toastWithButton) {
      toastWithButton = f7.toast.create({
        text: 'Toast with additional close button',
        closeButton: true,
      });
    }
    // Open it
    toastWithButton.open();
  }
  function showToastWithCustomButton() {
    // Create toast
    if (!toastWithCustomButton) {
      toastWithCustomButton = f7.toast.create({
        text: 'Custom close button',
        closeButton: true,
        closeButtonText: 'Close Me',
        closeButtonColor: 'red',
      });
    }
    // Open it
    toastWithCustomButton.open();
  }
  function showToastWithCallback() {
    // Create toast
    if (!toastWithCallback) {
      toastWithCallback = f7.toast.create({
        text: 'Callback on close',
        closeButton: true,
        on: {
          close() {
            f7.dialog.alert('Toast closed');
          },
        },
      });
    }
    // Open it
    toastWithCallback.open();
  }

  function onPageBeforeOut() {
    f7.toast.close();
  }

  function onPageBeforeRemove() {
    // Destroy toasts when page removed
    if (toastBottom) toastBottom.destroy();
    if (toastTop) toastTop.destroy();
    if (toastCenter) toastCenter.destroy();
    if (toastIcon) toastIcon.destroy();
    if (toastLargeMessage) toastLargeMessage.destroy();
    if (toastWithButton) toastWithButton.destroy();
    if (toastWithCustomButton) toastWithCustomButton.destroy();
    if (toastWithCallback) toastWithCallback.destroy();
  }
</script>

// kitchen-sink/react/src/pages/toast.jsx
import React from 'react';
import { Navbar, Page, Block, Button } from 'framework7-react';

export default class extends React.Component {
  constructor(props) {
    super(props)
  }
  render() {
    return (
      <Page onPageBeforeRemove={this.onPageBeforeRemove.bind(this)} onPageBeforeOut={this.onPageBeforeOut.bind(this)}>
        <Navbar title="Toast" backLink="返回"></Navbar>
        <Block strong>
          <p>Toasts provide brief feedback about an operation through a message on the screen.</p>
          <p>
            <Button fill onClick={this.showToastBottom.bind(this)}>Toast on Bottom</Button>
          </p>
          <p>
            <Button fill onClick={this.showToastTop.bind(this)}>Toast on Top</Button>
          </p>
          <p>
            <Button fill onClick={this.showToastCenter.bind(this)}>Toast on Center</Button>
          </p>
          <p>
            <Button fill onClick={this.showToastIcon.bind(this)}>Toast with icon</Button>
          </p>
          <p>
            <Button fill onClick={this.showToastLargeMessage.bind(this)}>Toast with large message</Button>
          </p>
          <p>
            <Button fill onClick={this.showToastWithButton.bind(this)}>Toast with close button</Button>
          </p>
          <p>
            <Button fill onClick={this.showToastWithCustomButton.bind(this)}>Toast with custom button</Button>
          </p>
          <p>
            <Button fill onClick={this.showToastWithCallback.bind(this)}>Toast with callback on close</Button>
          </p>
        </Block>
      </Page>
    );
  }
  showToastBottom() {
    const self = this;
    // Create toast
    if (!self.toastBottom) {
      self.toastBottom = self.$f7.toast.create({
        text: 'This is default bottom positioned toast',
        closeTimeout: 2000,
      });
    }
    // Open it
    self.toastBottom.open();
  }
  showToastTop() {
    const self = this;
    // Create toast
    if (!self.toastTop) {
      self.toastTop = self.$f7.toast.create({
        text: 'Top positioned toast',
        position: 'top',
        closeTimeout: 2000,
      });
    }
    // Open it
    self.toastTop.open();
  }
  showToastCenter() {
    const self = this;
    // Create toast
    if (!self.toastCenter) {
      self.toastCenter = self.$f7.toast.create({
        text: 'I\'m on center',
        position: 'center',
        closeTimeout: 2000,
      });
    }
    // Open it
    self.toastCenter.open();
  }
  showToastIcon() {
    const self = this;
    // Create toast
    if (!self.toastIcon) {
      self.toastIcon = self.$f7.toast.create({
        icon: self.$theme.ios || self.$theme.aurora ? '<i class="f7-icons">star_fill</i>' : '<i class="material-icons">star</i>',
        text: 'I\'m on center',
        position: 'center',
        closeTimeout: 2000,
      });
    }
    // Open it
    self.toastIcon.open();
  }
  showToastLargeMessage() {
    const self = this;
    // Create toast
    if (!self.toastLargeMessage) {
      self.toastLargeMessage = self.$f7.toast.create({
        text: 'This toast contains a lot of text. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil, quae, ab. Delectus amet optio facere autem sapiente quisquam beatae culpa dolore.',
        closeTimeout: 2000,
      });
    }
    // Open it
    self.toastLargeMessage.open();
  }
  showToastWithButton() {
    const self = this;
    // Create toast
    if (!self.toastWithButton) {
      self.toastWithButton = self.$f7.toast.create({
        text: 'Toast with additional close button',
        closeButton: true,
      });
    }
    // Open it
    self.toastWithButton.open();
  }
  showToastWithCustomButton() {
    const self = this;
    // Create toast
    if (!self.toastWithCustomButton) {
      self.toastWithCustomButton = self.$f7.toast.create({
        text: 'Custom close button',
        closeButton: true,
        closeButtonText: 'Close Me',
        closeButtonColor: 'red',
      });
    }
    // Open it
    self.toastWithCustomButton.open();
  }
  showToastWithCallback() {
    const self = this;
    // Create toast
    if (!self.toastWithCallback) {
      self.toastWithCallback = self.$f7.toast.create({
        text: 'Callback on close',
        closeButton: true,
        on: {
          close() {
            self.$f7.dialog.alert('Toast closed');
          },
        },
      });
    }
    // Open it
    self.toastWithCallback.open();
  }
  onPageBeforeOut() {
    const self = this;
    self.$f7.toast.close();
  }
  onPageBeforeRemove() {
    const self = this;
    // Destroy toasts when page removed
    if (self.toastBottom) self.toastBottom.destroy();
    if (self.toastTop) self.toastTop.destroy();
    if (self.toastCenter) self.toastCenter.destroy();
    if (self.toastIcon) self.toastIcon.destroy();
    if (self.toastLargeMessage) self.toastLargeMessage.destroy();
    if (self.toastWithButton) self.toastWithButton.destroy();
    if (self.toastWithCustomButton) self.toastWithCustomButton.destroy();
    if (self.toastWithCallback) self.toastWithCallback.destroy();
  }
};
